source("./scripts/RGG/geodata.R")
source("./scripts/RGG/graph.R")
source("./scripts/RGG/simulate.R")
source("./scripts/RGG/plot.R")
source("./scripts/RGG/persistence.R")
source("./scripts/RGG/SIRJ_confidence.R")